### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by janupan** [katalon-studio/katalon-analytics#55]
- Katalon Studio Version:
- OS Version:
- Browser Version:

Steps to Reproduce:

1. open Katalon analytics
2. input email and password
3. go to your project

Blank result if I run my test suite, like a picture

Expected behavior: 
Show the data

Screenshots:
<img width="1440" alt="Screen Shot 2019-04-24 at 14 07 17" src="https://user-images.githubusercontent.com/18500720/56639277-7c6c9b80-669a-11e9-966f-a22868fef62b.png">

**Comment by kelson-pereira** [comment]
Hi guys,

I believe this is a comprehensive problem.
I am no longer successful in uploading reports to Analytics.
To help identify the root cause, here are some more tests I did:

1) OS: LINUX > KatalonStudio: 6.1.1 > Run Test Suite > Show in Analytics [FAIL]
2) OS: WINDOWS 7 > KatalonStudio: 6.1.1 > Run Test Suite > Show in Analytics [FAIL]
3) OS: MACOS > KatalonStudio: 6.1.2 > Run Test Suite > Show in Analytics [FAIL]

While the test suite is running, the results of the tests are presented in Analytics. However, upon completion of execution, all results are displayed as "0" (zero) and loading spinner does not end.

![Captura de Tela 2019-04-24 às 20 19 17](https://user-images.githubusercontent.com/47066976/56700010-5f51c000-66ce-11e9-85ed-9089d144c670.png)

**Comment by thongmgnguyen** [comment]
Hi,
We faced a performance issue last week. A fixed version was deployed yesterday.
